### ISSUE TITLE
Install several apps requiring root path

### ISSUE THREAD

**Issue by freeplanyo** [scith/redirect_ynh#3] opened 2016-05-16 01:20 UTC
Gitlab and mattermost both require root paths for example.

If installed first, rocker/shiny can be set to a specific directory and ran alongside an app requiring root path.

**Comment by scith** [comment] 2016-05-16 08:39
Hi,
For apps requiring root paths, I suggest using subdomains. I don't know of a way to make these apps work using only Nginx, as the problem is within the apps themselves.

For Shiny, I see two possibilities:

- Create the container, redirect on root, set up the path, remove the redirect, and reinstall the redirect on path
- Or create the container, redirect on path, open the port used by Shiny (eg 3838), setup Shiny using the port, close the port again

Cheers

**Comment by freeplanyo** [comment] 2016-05-16 13:17
Hey,
Can I set up subdomains on Yunohost domains ? I tried to create other domains but they were not reachable. The issue is discussed here https://forum.yunohost.org/t/can-not-access-the-domain-other-then-the-default-domain/191/6The 

Gitlab seems to have worked on it and resolved their issue https://github.com/gitlabhq/gitlabhq/pull/2162

Shiny works well on my install there's no problem, it was an example of an app working on non root path.

In a related note, to install several redirect apps, it would be great to specify the name of the app and add an option to add new redirects once it is installed. For now redirect must be installed twice to use several, e.g. shiny, instances and the created apps have the same name.
I can do a PR for the app name but am not sure how to add an option to add new redirects.

Cheers

**Comment by scith** [comment] 2016-05-16 14:01
Hi, I don't know about noho.st subdomains sorry. I have my own domain name so I just point the subdomain to my server's IP and add that subdomain to YNH. Everything works fine.

As for the app names, do you mean in the admin panel or in the user portal? The user portal does have app names, but the admin panel just got them recently. See issue here: https://dev.yunohost.org/issues/41

**Comment by freeplanyo** [comment] 2016-05-16 14:47
Ok thanks. I would like to use noho.st domains if possible.

The app names seem related to multi instances apps indeed.

I am using docker-compose for gitlab and there seems to be an option for relative paths:
https://hub.docker.com/r/sameersbn/gitlab - section Deploy to a subdirectory (relative url root)
https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml#L30

But I can't get it to work for now...

**Comment by scith** [comment] 2016-05-16 16:40
Perhaps by running the container using the flag then? 
`--env 'GITLAB_RELATIVE_URL_ROOT=/git'`

Also there seems to be a gitlab app for YNH already, doesn't it cover your need?
Incidentally, I also have a Docker container app https://github.com/scith/docker_container_ynh and a DockerUI app https://github.com/scith/dockerui_ynh

I close this issue for now if that is OK with you, as I don't see a way of solving your problem within this app scope.

Cheers

**Closed by scith** 2016-05-16 16:40 UTC

**Comment by freeplanyo** [comment] 2016-05-21 12:19
Thanks I didn't see the ynh gitlab app. But it installs on root so same problems as when installing with redirect (can't install other apps after). Dockerui would be great but my yunhost is already dockerized and I have issues with privileged containers https://github.com/docker/docker/issues/4040.

It could still be a nice to have feature for users with no subdomains perhaps ? I'm not sure if it's possible.

**Comment by scith** [comment] 2016-05-21 16:21
Hmmm I don't see how such feature could be implemented. The problem really lies in the individual applications that are not properly configured or developed to allow for nginx paths.

If you have any idea of how we could solve this using nginx only it would be welcome. I find Nginx really difficult to understand and debug so any help is welcome

**Comment by freeplanyo** [comment] 2016-05-21 19:32
Ok thanks. I don't know much about nginx but I may look into it. I got gitlab working with their options btw but same issue with [mautic](https://github.com/mautic/docker-mautic).

Cheers
